export const StorageActionTypes = {
  ADD_CURRENT_USER: 'ADD_CURRENT_USER',
  DELETE_CURRENT_USER: 'DELETE_CURRENT_USER',
  STORAGE_TOGGLE_BEARER: 'STORAGE_TOGGLE_BEARER',
  SET_CART_COUNT: 'SET_CART_COUNT',
  PLUS_CART_COUNT: 'PLUS_CART_COUNT',
  SUBTRACT_CART_COUNT: 'SUBTRACT_CART_COUNT',
  CREATE_ANONYMOUS_ID: 'CREATE_ANONYMOUS_ID',
  ADD_RECENTLY_DEVICE: 'ADD_RECENTLY_DEVICE'
}
