apiVersion: v1
kind: Service
metadata:
  name: web-client
  namespace: ci

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: web-client

  ports:
    - name: http
      port: 30081
      nodePort: 30081

  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-client
  namespace: ci
spec:
  # minReadySeconds: 30
  selector:
    matchLabels:
      app: web-client
  replicas: 2
  template: # template for the pods
    metadata:
      labels:
        app: web-client
    spec:
      containers:
        - name: web-client
          image: dingtoi/web-client:v1
