export const ScreenActionTypes = {
  SET_LANGUAGE: 'SET_LANGUAGE',
  ADD_STAGE: 'ADD_STAGE',
  ADD_LAYER: 'ADD_LAYER',
  ADD_IMAGE: 'ADD_IMAGE',
  CLEAR_STAGE: 'CLEAR_STAGE',
  CLEAR_LAYER: 'CLEAR_LAYER',
  CLEAR_IMAGE: 'CLEAR_IMAGE'
}
