export default {
  nephalim: 'Nephalim',
  forest_elf: 'Wood Elf',
  celtic: 'Celtic',
  chaos: 'Chaos',
  dwarf: 'Dwarf',
  slavic: 'Slavic',
  lizard: 'Lizardman',
  nightelf: 'Dark Elf',
  lich: 'Lich',
  nippon: 'Nippon',
  britain: 'Britain',
  highelf: 'High Elf',
  espana: 'Espana',
  cathay: 'Cathay',
  eurasia: 'Arab',
  demon: 'Demon',
  vampire: 'Vampire',
  viking: 'Viking',
  german: 'German',
  greek: 'Greek-Roman',
  orc: 'Orc',
  mongol: 'Mongol',
  barbarian: 'Barbarian',
  india: 'India',
  persia: 'Persia',
  africa: 'Africa',
  israel: 'Israel',
  beastman: 'Beastman',
  native: 'Native'
}