export const UserActionTypes = {
  EMAIL_LOGIN_START: 'EMAIL_LOGIN_START',
  EMAIL_LOGIN_SUCCESS: 'EMAIL_LOGIN_SUCCESS',
  EMAIL_LOGIN_FAILED: 'EMAIL_LOGIN_FAILED',
  REGISTRATION_START: 'REGISTRATION_START',
  REGISTRATION_SUCCESS: 'REGISTRATION_SUCCESS',
  REGISTRATION_FAILED: 'REGISTRATION_FAILED',
  CHECK_EMAIL_START: 'CHECK_EMAIL_START',
  CHECK_EMAIL_SUCCESS: 'CHECK_EMAIL_SUCCESS',
  CHECK_EMAIL_FAILED: 'CHECK_EMAIL_FAILED',
  LOGOUT_START: 'LOGOUT_START',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_FAILED: 'LOGOUT_FAILED',
  CONFIRM_EMAIL_START: 'CONFIRM_EMAIL_START',
  CONFIRM_EMAIL_SUCCESS: 'CONFIRM_EMAIL_SUCCESS',
  CONFIRM_EMAIL_FAILED: 'CONFIRM_EMAIL_FAILED',
  CLEAR_CHECK_EMAIL: 'CLEAR_CHECK_EMAIL'
}
